### ISSUE TITLE
add `VariantPrismGenerator` for `elm-accessors` unnamed

### ISSUE THREAD

**Issue by lue-bird** [lue-bird/elm-review-missing-record-field-lens#5]
The default `VariantPrismGenerator` named `accessors` generates _named_ [`Accessors` by @erlandsona](https://dark.elm.dmy.fr/packages/erlandsona/elm-accessors/latest/).
The unnamed version is for users of [`bChiquet/elm-accessors`](https://dark.elm.dmy.fr/packages/bChiquet/elm-accessors/latest/) or those should help transition to named [`erlandsona/elm-accessors`](https://dark.elm.dmy.fr/packages/erlandsona/elm-accessors/latest/).

**Comment by erlandsona** [comment]
My version is fully backwards compatible with bChiquet's... so there shouldn't be anything that prevents people from trying out my version which just has more accessors built in.

**Comment by erlandsona** [comment]
The `named` vs `unnamed` is mostly irrelevant until I figure out the rest of this Form abstraction I've been doing all of this to support.

**Comment by lue-bird** [comment]
But the named and unnamed accessor types are not compatible, right?

**Comment by erlandsona** [comment]
>But the named and unnamed accessor types are not compatible, right?

They ARE compatible. This is what I've been trying to say. I explicitly made them all backwards compatible.

**Comment by lue-bird** [comment]
Nah, we're still talking past each other.
Defining the variant prisms by `Accessors.makeOneToN_` which is what you PRed and what I'd like to keep as the default is only available in your package, not in bChiquets.

**Comment by erlandsona** [comment]
Ah yup, got it. Correct. 
I'm using the "extended" version for generating lenses with unique names but my version of the package keeps the same module heirarchy as bChiquets so the generator for the unnamed version should still work for both packages.

👌
